### ISSUE TITLE
cannot open 'XXX' for reading: Input/output error

### ISSUE THREAD

**Issue by regomne** [efrecon/docker-webdav-client#20]
Docker compose file:

```yaml
version: "3.0"
services:
  davfs:
    image: efrecon/webdav-client:latest
    container_name: davfs
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    environment:
      - WEBDRIVE_USERNAME=XXX
      - WEBDRIVE_PASSWORD=XXXX
      - WEBDRIVE_URL=https://XXXXX
      - DAVFS2_ASK_AUTH=0
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes:
      - /srv/davfs:/mnt/webdrive:rshared
```

Sucessfully mounted and could `ls` the files and directories. However, files can't be read. It show `Input/output error` when `cp` or `cat`.

Additional information: the webdav returns HTTP 302 for files to redirect to other location.
