### ISSUE TITLE
Stopping or restarting the container leads to persistent PID file

### ISSUE THREAD

**Issue by cubic3d** [efrecon/docker-webdav-client#8]
I have a weird problem: After stopping or restarting the container the PID file `/var/run/mount.davfs/mnt-webdrive.pid` is not getting removed and prevents any further starts of the container (requires to destroy or delete the .pid file from the container's file system).
```
adduser: uid '33' in use
chown: unknown user webdrive
Mounted https://dav-url-was-here onto /mnt/webdrive

Terminated
Caught TERM! Unmounting /mnt/webdrive...
Forwarding TERM to 14
adduser: uid '33' in use
chown: unknown user webdrive
found PID file /var/run/mount.davfs/mnt-webdrive.pid.
Either /mnt/webdrive is used by another process,
or another mount process ended irregular
mount: mounting https://dav-url-was-here on /mnt/webdrive failed: No such device
Nothing found in /mnt/webdrive, giving up!
```
If I exec into the container and unmount the dav file system the .pid disappears. I'm not sure where to look, because I see the trap working but it always seems to forward the TERM signal to the devfs2 process, which means that unmount didn't stop the process (it does so if I unmount by hand). Any ideas?

BTW no special config:
```
services:
  storage:
    image: efrecon/webdav-client
    restart: unless-stopped
    command: empty.sh
    environment:
      - WEBDRIVE_URL=https://{{ lookup('env','DAV_USERNAME') }}.dav-url-was-here
      - WEBDRIVE_USERNAME={{ lookup('env','DAV_USERNAME') }}
      - WEBDRIVE_PASSWORD={{ lookup('env','DAV_PASSWORD') }}
      - OWNER=33
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    volumes:
      - /mnt/app/data:/mnt/webdrive:rshared
```
